apiVersion: v1
data:
    password: ENC[AES256_GCM,data:/5nrbX49iBB+9b7/,iv:Tn/cpcqDT6fAw8ahwgCYmWdZ0Ek5mgGBi/5NOU7WsWQ=,tag:2DQ2l5ebdZgTX4cJ/t8CyQ==,type:str]
    user: ENC[AES256_GCM,data:bnGWavy99pc=,iv:It13Ih8tl/orgHJY9+rblSrTFRACxfffzfX/WX1Iwmg=,tag:pX4yNpD27QNO+0ddUX11Ew==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-03T12:24:18Z"
    mac: ENC[AES256_GCM,data:iN06glYqhV3e/wBHQpf4ME9fkbo87FStz6i9B4lXBtPhtFPseQZ4omm3kPrRxuEn0S8A67pHmTSV6diUpD0Dg+K0OIs217d/k2OhDq2D5oXyV+KG5EJQswRSNRlKDM8/aDv5nk4JT/DBNMSx49CMgYnQTmKhOVU1a1cS9oc4wRo=,iv:5ze+4ncyaEOlFowmg7EIVdbd0GVBTH6bBtK4Sg5gJ8g=,tag:dzOIoDmgb6sBx4Av6LZpPg==,type:str]
    pgp:
        - created_at: "2022-05-03T12:24:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw+D/kuLWK+sAQ/+KPgwAZQncUz9KdDJV3y85apoqZ8uEURbdU39p/nA0y1T
            lEXaV50+Z0lgdcRVzp5LEu4oI38KO6pqjjd36kD3pvN7GTAVI/JsmwXOA50uaQCC
            f+etBBeGCD8tyk7ahLcDMQ8UWaGN+S7AA4Wh8aM9ym8Kk3Xkly+mT7YGhE511062
            oGiXmT3PasWZ9DtN1JuRTFH4CsVDQERjXLV1fK5FqrMpPdb9vrW6Y9N+QCq7CtZG
            z+wgdzfljnZue9hGGdwHP0WkzugYzQwyW/qgYDUDnTzSMHwuZbiYmEiEnIammaON
            NMSI5e8sn32Fb1ln6RDW9aoeJSYiOigSewtNwBnxfv7s1oOE0aszsFonBwllmBkY
            Ge2hwethpUBtDSyzOAD0n2BrdvbFr3E1B3OOH8B6JvlRAOreMLZCXSh8ejVjgdJR
            7YtdTNf1Ji7Sd7AUpwfhcShDxe53Ygy03DZMj1lrddeCZcMuPwJjA9Lfays9Z3Eq
            xPP9lE2/58i3pMtXSEis1WBuwRKIp3yChycaD75hwU5AOwbhk0QIeZPvtzavDS3g
            xaotGMwMq6xkqISCmBbBF46xu5iwkCGyU3tiNQLHWQvLQgaqMxagjfXh/+yAQX2w
            tjxk/j5L2uoCmUxYb4Ipta6dH74xWLTYvstBoRB/qAVJTtv5Oxlf7yuUWiXJXQnS
            XgHrUvMdVJpjULC+vRPuzvlptkhqeTavplCvqtqPrUowjsvEofqEzkDPFfycUcmi
            mKy0Chxy1byf0BEMjHCUIngGACQ/bmJHdWFGDfD8l9pW+M/5UIQTfIgS+dafYrg=
            =NbwM
            -----END PGP MESSAGE-----
          fp: 220D9278AC50F110AB373D529A65BC78CD619514
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
